### ISSUE TITLE
[deprecated] 리소스 찾을때 팁

### ISSUE THREAD

**Issue by 00125** [yjcpaj4/play_with_us#10]
구글링할때 설정에서 고급검색 클릭 후

사용권한에서 사용, 공유 또는 수정가능(상업적 용도 포함) 으로 수정하여 이미지 검색ㄱㄱ

**Comment by EUNJAESHIN** [comment]
좋은 팁이네요

**Comment by aw9223** [comment]
프로젝트 중심으로 가야하는데 팁중심으로 가버려서 제목을 좀 바꿨다 씨ㅃ색햐
