### ISSUE TITLE
게임 제목

### ISSUE THREAD

**Issue by hw00389** [yjcpaj4/play_with_us#12]
ex) whisper in the dark ( 어둠속에서의 속삭임)

**Comment by hw00389** [comment]
Curse of the bloodstained doll ( 피묻은 인형의 저주)

**Comment by hw00389** [comment]
Doll and hide and seek ( 인형과 숨바꼭질 )

**Comment by hw00389** [comment]
OnOff

**Comment by hw00389** [comment]
Cursed house ( 저주받은 집(저택) )

**Comment by EUNJAESHIN** [comment]
Into the darkness
Whisper of the evil
Possession

**Comment by EUNJAESHIN** [comment]
인형찾기

**Comment by EUNJAESHIN** [comment]
인형놀이

**Comment by 00125** [comment]
Echoes of dolls

**Comment by 00125** [comment]
아니 저기요

**Comment by fukeric** [comment]
공포영화들중에 대부분은 임팩트있는 인물의 이름을 제목으로하는경우가 많음 ㅎ

**Comment by hw00389** [comment]
Play With Us ( 우리와 같이 놀자) 확정 되었습니다.

투표 결과

Play With Us  4 : 1  Play With me
