### ISSUE TITLE
엔딩 스토리

### ISSUE THREAD

**Issue by hw00389** [yjcpaj4/play_with_us#16]

**Comment by hw00389** [comment]
Sad Ending : 게임 도중 주인공이 죽으면 게임 오버 화면이 뜨고  다시 화면이 밝아진다. 그리고 미아를 찾습니다. 라는 전단지가 붙여져 있다. 그리고 다시 화면이 어두워 졌다가 밝아지면서 오프닝 스토리에서 나왔던 놀이터 장면이 나온다. 그리고 소녀 귀신은 또 다른 소년(소녀)를 기다린다. 그러던 중 어떤 소년(소녀)가 다가 오고 소년(소녀) : " 혼자서 놀기 심심하지 않아? " 라고 말하고 3초 뒤에 소녀 귀신은 웃음 소리를  내면서 게임은 종료 된다.

Happy Ending : 주인공이 모은 인형들을 책에서 얻은 힌트를 가지고 소멸 시킨다. 그리고 소녀 귀신이 따라오고 있기 때문에 소멸 시킨 후 신속히 나간다. 나가는 동시에 Happy Ending 이 나온다. 그리고 집 앞 화면이 나오는데 밖은 화창하고 집은 애초에 없었던 것이다. 그리고 3초 뒤에 게임은 종료 된다.

**Comment by fukeric** [comment]
기획 의도가 바뀌어 해당 이슈는 진행되지 않습니다.
