### ISSUE TITLE
클라이막스

### ISSUE THREAD

**Issue by hw00389** [yjcpaj4/play_with_us#17]

**Comment by hw00389** [comment]
FINAL STAGE

인형은 모두 획득 하였다.

숨어 있다가 주인공은 나와서 2층 화장실에 있는 열쇠를 가지고 출입문을 열러 1층으로 간다.

1층으로 내려가면 동영상이 나오고 소녀 귀신이 얘기한다.

“ 어디가려고...?  같이 놀기로 했잖아!!!”(예시)

소녀 귀신이 인형을 들고 영혼을 주입하기 위해서 계속해서 달려온다. 주인공은 재치를 발휘해서 책에서 얻은 힌트를 이용, 모은 인형들을 여러 가지 방법을 통해서 제거하고 출입문을 나가면 게임은 종료된다.

**Comment by fukeric** [comment]
기획 의도가 바뀌어 해당 이슈는 진행되지 않습니다.
