### ISSUE TITLE
[deprecated] 효과음 저작물

### ISSUE THREAD

**Issue by EUNJAESHIN** [yjcpaj4/play_with_us#19]
이제부터 이 이슈에 코멘트로 링크를 남겨주세요

**Comment by EUNJAESHIN** [comment]
http://www.hanac200x.jp/
http://soundarbour.sakura.ne.jp/BGM.html
http://www.vita-chi.net/sozai1.htm
http://www.presence-of-music.com/horror_suspence.html

**Comment by hw00389** [comment]
http://www.soundbible.com

**Comment by fukeric** [comment]
이제부터 리소스관련은 드롭박스에서 관리됩니다.
