### ISSUE TITLE
오프닝, 엔딩영상을 위한 동영상 플레이어 모듈제작

### ISSUE THREAD

**Issue by fukeric** [yjcpaj4/play_with_us#25]

**Comment by hw00389** [comment]
package asd;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.scene.paint.Color;
/**
 *
- @author NN
  */
  public class asd extends Application {
  
  /**
  - @param args the command line arguments
    */
    public static void main(String[] args) {
    launch(args);
    }
  
  @Override
  public void start(Stage stage) throws Exception {
  
  ```
  Group root = new Group();
  Media med = new Media("file:///K://asd.flv");       
  MediaPlayer mediaP = new MediaPlayer(med);
  MediaView view=new MediaView(mediaP);
  
  root.getChildren().add(view);
  
  
  stage.show();
  mediaP.play();
  ```
  
  }
  }

사운드는 나오는데 화면은 안보입니다.

**Comment by hw00389** [comment]
package asd;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class asd extends Application {

```
public static void main(String args[]) {

    launch(args);
}
```

public void start(Stage stage) throws Exception {

```
Group root = new Group();

Media media = new Media("file:///K:/asd.flv");
MediaPlayer player = new MediaPlayer(media);
MediaView view = new MediaView(player);

root.getChildren().add(view);
Scene scene = new Scene(root, 400, 400, Color.BLACK);
stage.setScene(scene);
stage.show();

player.play();
```

}
}

사운드는 나오는데 화면은 안보입니다.

**Comment by hw00389** [comment]
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Color;

import javax.swing.JFrame;
import javax.swing.JPanel;

import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;

import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.player.embedded.windows.Win32FullScreenStrategy;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

public class Media {

```
public static void main(String[] args) {

    JFrame f = new JFrame();
    f.setLocation(100, 100);
    f.setSize(1000, 600);
    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    f.setVisible(true);


    Canvas c = new Canvas();

    c.setBackground(Color.black);

    JPanel p = new JPanel();
    p.setLayout(new BorderLayout());

    p.add(c);
    f.add(p);


    NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(),"C:/Program Files (x86)/VideoLAN/VLC");
    Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);

    MediaPlayerFactory mpf = new MediaPlayerFactory();

    EmbeddedMediaPlayer emp = mpf.newEmbeddedMediaPlayer(new Win32FullScreenStrategy(f));
    emp.setVideoSurface(mpf.newVideoSurface(c));

    emp.toggleFullScreen();

    emp.setEnableMouseInputHandling(false);

    emp.setEnableKeyInputHandling(false);

    String file = "asd.mp4";

    emp.prepareMedia(file);

    emp.play();
}
```

}

오류 메세지

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'libvlc': JNA native support (win32-amd64/libvlc.dll) not found in resource path (C:\Users\Use\workspace\Media\vlcj-3.0.1-dist\vlcj-3.0.1-dist\vlcj-3.0.1\jna-3.5.2.jar;C:\Users\Use\workspace\Media\bin;C:\Users\Use\workspace\Media\vlcj-3.0.1-dist\vlcj-3.0.1-dist\vlcj-3.0.1\platform-3.5.2.jar;C:\Users\Use\workspace\Media\vlcj-3.0.1-dist\vlcj-3.0.1-dist\vlcj-3.0.1\vlcj-3.0.1.jar)
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:220)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:322)
    at com.sun.jna.Library$Handler.<init>(Library.java:142)
    at com.sun.jna.Native.loadLibrary(Native.java:387)
    at com.sun.jna.Native.loadLibrary(Native.java:366)
    at Media.main(Media.java:40)

**Comment by fukeric** [comment]
https://github.com/axet/play 의 라이브러리를 사용하여 완료하였습니다.
