### ISSUE TITLE
아이템 창

### ISSUE THREAD

**Issue by hw00389** [yjcpaj4/play_with_us#34]

**Comment by hw00389** [comment]
- 키보드 'I' 버튼을 누르면 소지품 창이 열린다.

**Comment by fukeric** [comment]
소지품창 UI 는 생각해봐야함.

메이플스토리처럼할것인지 더 간단하게 할수있을지...

**Comment by hw00389** [comment]
- 다른 아이템 창 -
  아이템 창이 세로로 글자로 나온다.
  ex)
  책
  칼
  열쇠 꾸러미

**Comment by fukeric** [comment]
기획의 방향이 틀어져 해당이슈는 진행되지 않습니다.
