### ISSUE TITLE
[deprecated] Sprite 제작 툴

### ISSUE THREAD

**Issue by EUNJAESHIN** [yjcpaj4/play_with_us#39]
1. 하나 하나 연속된 동작을 개별이미지로 자동으로 분리하기
2. 연속된 동작의 이미지를 합쳐서 한 이미지로 만들기
3. 개별 프레임을 하나의 이미지로 합치기

**Comment by fukeric** [comment]
Sprite 제작툴은 프로젝트 생성하여 관리합니다.
