### ISSUE TITLE
[deprecated] 새로운 금연 캠페인을 시작합니다

### ISSUE THREAD

**Issue by EUNJAESHIN** [yjcpaj4/play_with_us#4]
**2016-09-26 ~ 2016-10-31**

우리 조원은 건강 증진을 위해 월간 금연 캠페인을 시작하겠습니다
이하 참가자 명단 및  결의문
1. 차명도 **"금연에 실패 시, 1주 동안 맨발로 학교생활"**
2. 김윤환 **"금연에 실패 시, 1주 동안 10걸음 마다 팔굽혀펴기 10회 실시"**
3. 김정현 **"금연에 실패 시, 2주 동안 [혼밥티](http://upload2.inven.co.kr/upload/2016/08/06/bbs/i12025790234.jpg) 입고 다니기"**

**만약 몰래 흡연을 해서 금연 캠페인을 깬다면 결의 사항 모두 이행**

**Comment by fukeric** [comment]
혼밥티는 [여기](http://upload2.inven.co.kr/upload/2016/08/06/bbs/i12025790234.jpg)를 참조하시기 바랍니다.

**Comment by aw9223** [comment]
후.... 피고싶어요 ㅎㅎ
