### ISSUE TITLE
리소스를 외부서버에서 다운받아오기

### ISSUE THREAD

**Issue by ckckck23** [yjcpaj4/play_with_us#45]
동영상, 이미지, 효과음, 배경음의 용량으로 초기에 게임용량이 비대해져 초기 리소스는 외부에서 받아오게 처리하기

**Comment by fukeric** [comment]
자체적으로 서버를 운영하기에는 부담이 되어 클라우드를 제공해주는 서버를 찾아야할듯

**Comment by fukeric** [comment]
https://www.dropbox.com/developers

드롭박스에서 개발자 API 를 제공하고있음 이걸로 해봄 ^오^
