### ISSUE TITLE
[deprecated ]건의사항

### ISSUE THREAD

**Issue by fukeric** [yjcpaj4/play_with_us#7]
1. 사운드 편집 프로그램 사용법을 익혀 두면 좋겠다.(골드웨이브 등)
2. 간단한 동영상 편집을 도와주면 작업 효율이 높아질것같다. (프리미어를 이용하여 동영상 컷 자르기)

**Comment by fukeric** [comment]
이 글은 정현이가 싸지른 글입니다. 말투가 좀 띠겁네요

**Comment by 00125** [comment]
뿌직
