### ISSUE TITLE
긴장요소

### ISSUE THREAD

**Issue by EUNJAESHIN** [yjcpaj4/play_with_us#8]
사운드를 활용해 플레이어에게 공포감을 조성할 요소

EX) 
1. 라디오에서 들리는 노이즈 소리
2. 손전등을 껐을 때  들리는 귀신 웃음소리

**Comment by fukeric** [comment]
효과음은 어디서 구해야할까용

**Comment by 00125** [comment]
와 ! 정말 좋은 생각입니다.

**Comment by hw00389** [comment]
제가 한번 찾아보겠습니다.

**Comment by EUNJAESHIN** [comment]
저도 한번 찾아보겠습니다.

**Comment by hw00389** [comment]
갑자기 창문 깨지는 소리
거실에서 들리는 천둥 소리와 함께 들리는 괘종시계 소리

**Comment by hw00389** [comment]
칼로 벽을 긁는 소리

**Comment by hw00389** [comment]
귀신의 발자국 소리

**Comment by hw00389** [comment]
지붕에서 피가 떨어지는 소리

**Comment by fukeric** [comment]
티비근처에 갔을경우 전원이 켜지고 노이즈 발생

**Comment by fukeric** [comment]
화장실에서 열쇠를 습득후 핏발자국, 거울깨기

**Comment by fukeric** [comment]
화장실에서 욕조옆 귀신출몰

**Comment by fukeric** [comment]
주기적으로 귀신이 나와 8초간 플레이어를 따라다님

**Comment by fukeric** [comment]
옷방에서 열쇠를 습득후 나가려는데 마네킨이 따라오는 액션

**Comment by fukeric** [comment]
소녀의 방에서 일기를 본뒤 노크소리가 들림
