### ISSUE TITLE
[deprecated] 방에 들어갔을 때, 귀신 출물

### ISSUE THREAD

**Issue by hw00389** [yjcpaj4/play_with_us#9]
ex) 귀신이 깜짝으로 나타나는 것이 아니라, 서서히 발자국소리, 웃음소리들이 점점 커지면서 나타난다.

**Comment by fukeric** [comment]
효과음 구할라면 힘들겠는데...??

**Comment by 00125** [comment]
사운드편집 프로그램을 사용이 필요해 보이네요 ^^*

**Comment by hw00389** [comment]
사용하기 쉬운 사운드 편집 프로그램인 'Gold Wave' 를 이용하면 될 것 같아요.

**Comment by fukeric** [comment]
여러가지 효과음을 듣고 다운 받을 수 있어서 참고가 될만한 자료사이트입니다.

http://soundbible.com/

김윤환(hw00389)이 찾은 주소입니다.
